server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8  
  
spring:
  datasource:
    url: jdbc:mysql://47.105.58.164:3306/qidian?characterEncoding=UTF-8
    username: root
    password: qidian@Xrt0203
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
 
  application:
    name: serviceSecurity #指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.105.58.164:9096/eureka/ #eureka服务注册地址 服务注册中心的配置内容，指定服务注册中心的Url
        
thymeleaf:
# 禁止浏览器缓存
 cache: false
 mode: HTML5
 
