server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8  
  
spring:
  datasource:
    url: jdbc:mysql://47.105.58.164:3306/qidian?characterEncoding=UTF-8
    username: root
    password: qidian@Xrt0203
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
 
     
        
thymeleaf:
# 禁止浏览器缓存
 cache: false
 mode: HTML5
 